[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "usman-062", email = "ahmadalibhatti62@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "google-generativeai>=0.8.6",
    "livekit-agents>=1.8.4",
    "ollama>=0.6.3",
    "openai>=2.54.0",
    "pydantic-settings>=2.15.0",
    "python-multipart>=0.0.32",
    "uvicorn>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
